---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-tls-externalsecret-from-eso-gcpsm
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-gcp-clstrsecstore
  target:
    name: harbor-gcp-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .fullchain  }}"
        tls.key: "{{ .privatekey }}"
  data:
    - secretKey: privatekey
      remoteRef:
        key: wildcard_dev1_nimbus_privatekey
    - secretKey: fullchain
      remoteRef:
        key: wildcard_dev1_nimbus_fullchain
