---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-externalsecret-from-eso-gcpsm
  namespace: harbor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-gcp-clstrsecstore
  target:
    name: harbor-gcp-secrets
    creationPolicy: Owner
  data:
    - secretKey: harbor-admin-password
      remoteRef:
        key: harbor-admin-initial-secret
    - secretKey: secretKey
      remoteRef:
        key: harbor-admin-secret-key
