apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-dev1-gcp
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://gitlab.es.net/platform-engineering/argocd-control3.git'
      path: manifests/harbor
      targetRevision: HEAD
    - repoURL: 'https://github.com/drshawnkwang/control-gkeargocd-pe-test3.git'
      targetRevision: HEAD
      ref: values
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.16.2
      helm:
        valueFiles:
          - $values/app-values/harbor-values.yaml
